# Generated by Django 5.1.2 on 2024-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Imagen de Perfil'),
        ),
    ]
