# Generated by Django 5.1.2 on 2024-11-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='rewardclaim',
            name='code',
            field=models.CharField(default='psVBTNLJlQ7y', max_length=12, unique=True),
        ),
    ]
