# Generated by Django 5.1.2 on 2024-11-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_reward_stock_alter_rewardclaim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='code',
            field=models.CharField(default='5SfrRW9gRbEY', max_length=12, unique=True),
        ),
    ]
