# Generated by Django 5.1.2 on 2024-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_rewardclaim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='code',
            field=models.CharField(default='DJ8gwkM69oqk', max_length=12, unique=True),
        ),
    ]
