# Generated by Django 5.1.2 on 2024-11-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_rewardclaim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='code',
            field=models.CharField(default='Rs8YfxA34rWz', max_length=12, unique=True),
        ),
    ]
