# Generated by Django 5.1.2 on 2024-11-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_reward_image_alter_rewardclaim_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardclaim',
            name='code',
            field=models.CharField(default='tverTLOL5amj', max_length=12, unique=True),
        ),
    ]
